### PR TITLE
Created 'help' and 'usage' command for #1 and #5

### PR DESCRIPTION
**Pull request by casperbakker**
Also added functions reply() and sendMessage() for a cleaner API

### CODE REVIEW

**Comment by trizz** [comment]
Great, thanks! But in the "help" you mention the "je bestelling" command, but I don't see an implementation of it?

**Comment by casperbakker** [comment]
Yeah, I meant that you can say "@frietbot: friet met"
Maybe it is nicer to create a command "@frietbot: bestel friet met", but I didn't want to change the existing commands

**Comment by trizz** [comment]
Ok, clear! Thanks for the PR, merging it now :smile: 

> Maybe it is nicer to create a command "@frietbot: bestel friet met"

I've considered that command, but I wanted to keep it clean and simple. But, when the functionality expands, maybe this is something to reconsider.

**Comment by casperbakker** [comment]
:+1:

**Pull request merged**
